#pragma once
// OpenRemote-Studio-Icon-Namen -> mdi-Namen (Katalog: mdi_icons.h).
// Studio schreibt iconName in devicePages-Items. Nicht gemappte Namen
// -> kein Icon, der Button zeigt seinen Text.
#include <cstdint>
namespace esphome { namespace menu_ui {
struct StudioIcon { const char *name; const char *mdi; };
static const StudioIcon STUDIO_ICONS[] = {
  {"apps", "movie-open"},
  {"aspect_ratio", "image"},
  {"audio_sound", "speaker"},
  {"av_receiver", "speaker"},
  {"back", "keyboard-return"},
  {"battery", "battery"},
  {"bluetooth", "bluetooth"},
  {"brightness", "brightness-6"},
  {"brightness_down", "brightness-6"},
  {"brightness_up", "brightness-6"},
  {"cast", "cast"},
  {"channel_down", "chevron-down"},
  {"channel_up", "chevron-up"},
  {"chromecast_dongle", "cast"},
  {"down", "arrow-down"},
  {"dpad", "gamepad-variant"},
  {"exit", "close"},
  {"fast_forward", "fast-forward"},
  {"favourite_star", "star"},
  {"guide_epg", "television"},
  {"hdmi", "television"},
  {"hdmi_dongle", "cast"},
  {"help", "information"},
  {"home", "home"},
  {"info", "information"},
  {"input_source", "television"},
  {"keyboard", "cellphone"},
  {"left", "arrow-left"},
  {"light_bulb", "lightbulb"},
  {"lights_off", "lightbulb"},
  {"lights_on", "lightbulb-on"},
  {"live_tv", "television"},
  {"lock", "lock"},
  {"menu", "menu"},
  {"microphone_voice", "microphone"},
  {"mute", "volume-off"},
  {"ok_select", "check"},
  {"pause", "pause"},
  {"picture_mode", "image"},
  {"play", "play"},
  {"power", "power"},
  {"projector", "television"},
  {"projector_screen", "television"},
  {"receiver_speaker", "speaker"},
  {"record", "record"},
  {"recordings", "record"},
  {"red_green_yellow_blue", "palette"},
  {"rewind", "rewind"},
  {"right", "arrow-right"},
  {"screen_off", "power-standby"},
  {"settings", "cog"},
  {"skip_next", "skip-next"},
  {"skip_previous", "skip-previous"},
  {"sleep_timer", "sleep"},
  {"stop", "stop"},
  {"streaming_app", "movie-open"},
  {"subtitles_cc", "movie"},
  {"tv", "television"},
  {"unlock", "lock-open-variant"},
  {"up", "arrow-up"},
  {"volume_down", "volume-minus"},
  {"volume_up", "volume-plus"},
  {"wifi", "wifi"},
};
static const int STUDIO_ICONS_COUNT = 63;
} }  // namespace
