"""GENERIERT (esphome/tools/einst_gen.py): Einstellungsseiten der Remote als Konfigurator-Seiten.
Eintraege t="setting" steuern die Widgets der eingebauten Seiten fern (open-remote-einstellungen.h)."""

EINST_SEITEN = [{'id': 'set_bright',
  'title': 'Bildschirm',
  'remember': True,
  'flow': True,
  'items': [{'t': 'text', 'label': 'Helligkeit', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'disp_bri_sld', 'label': 'Display', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_bri', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'kbd_light_btn', 'label': 'Tastenbeleuchtung', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_kbdon', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'kbd_bri_sld', 'label': 'Tastenbeleuchtung', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_kbdbri', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Ausschalten', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'to_sld', 'label': 'Display aus nach', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_to', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_dim_sld', 'label': 'Abdunkeln nach', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_dim', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_dimp_sld', 'label': 'Abdunkeln auf', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_dimp', 'label': '', 'w': 6, 'h': 0}]},
 {'id': 'set_show',
  'title': 'Anzeige',
  'remember': True,
  'flow': True,
  'items': [{'t': 'text', 'label': 'Statusleiste', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'show_ble_btn', 'label': 'Bluetooth-Symbol', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sh_ble', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'show_wifi_btn', 'label': 'WLAN-Symbol', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sh_wifi', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'show_batt_btn', 'label': 'Akkustand', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sh_batt', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'show_clock_btn', 'label': 'Uhrzeit', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sh_clock', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'show_assi_btn', 'label': 'Assistenten-Symbol', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sh_assi', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'show_motion_btn', 'label': 'Bewegungs-Symbol', 'w': 6, 'h': 1},
            {'t': 'text', 'label': 'Kurzes Symbol neben der Uhr, sobald die Remote eine Bewegung bemerkt.', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Cover', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'cover_player_btn', 'label': 'Cover Player', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_cov_p', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'cover_home_btn', 'label': 'Cover Startseite', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_cov_h', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'MENÜ', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'mem_sld', 'label': 'Menü merken für', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_mem', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'menu_close_sld', 'label': 'Menü schließen nach', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_menu_close', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Logos', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'sd_logos_btn', 'label': 'Logos von SD-Karte', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sd_logos', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Kamera auf dem TV', 'w': 6, 'h': 1},
            {'t': 'sensor',
             'label': 'Größe',
             'entity': 'input_select.tv_wz_kamera_groesse',
             'w': 6,
             'h': 1,
             'steps': [{'t': 'ha',
                        'svc': 'input_select.select_next',
                        'entity': 'input_select.tv_wz_kamera_groesse',
                        'data': {'cycle': 'true'}}]}]},
 {'id': 'set_power',
  'title': 'Energie & Wecken',
  'remember': True,
  'flow': True,
  'items': [{'t': 'text', 'label': 'WLAN', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_wifi_btn', 'label': 'WLAN-Sparmodus', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_wifi', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_wifimax_btn', 'label': 'Sparmodus stark (Ruhe)', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_wifimax', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_wifi_off_btn', 'label': 'WLAN aus im Ruhezustand', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_off', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_wifis_sld', 'label': 'WLAN aus nach', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_offs', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_wifitv_sld', 'label': 'WLAN aus bei TV an', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_wifitv', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Prozessor & bluetooth', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_cpu_sld', 'label': 'Prozessor drosseln', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_cpu', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_light_btn', 'label': 'Leichtschlaf', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'Bei gedrosseltem Prozessor schläft er zwischen Funk- und Tastenereignissen. WLAN und Bluetooth bleiben verbunden. '
                      'Halbiert etwa den Ruhestrom (gemessen 29.09.).',
             'w': 6,
             'h': 0},
            {'t': 'setting', 'src': 'ps_wfest_btn', 'label': 'WLAN-Schnellstart', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'Feste IP statt DHCP, spart beim Verbinden nach einem Neustart oder Tiefschlaf Zeit. Wirkt ab dem nächsten Start. '
                      'Die Kanalsuche wird immer übersprungen (Fast Connect).',
             'w': 6,
             'h': 0},
            {'t': 'setting', 'src': 'ps_wfrueh_btn', 'label': 'WLAN früh einschalten', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'Ist das WLAN im Ruhezustand aus, schalten es auch Tasten und Bewegung wieder ein, ohne das Display zu wecken. Das '
                      'Ausschalten zählt ab der letzten Taste oder Bewegung.',
             'w': 6,
             'h': 0},
            {'t': 'setting', 'src': 'ps_bleidle_btn', 'label': 'BLE-Verbindung langsam', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_ble', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_bles_sld', 'label': 'BLE langsam nach', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_bles', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Aufwecken', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'motion_mode_lbl', 'label': 'Aufwecken bei', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'mm_0', 'label': 'Aus', 'w': 2, 'h': 1},
            {'t': 'setting', 'src': 'mm_1', 'label': 'Bewegung', 'w': 2, 'h': 1},
            {'t': 'setting', 'src': 'mm_2', 'label': 'Hochheben', 'w': 2, 'h': 1},
            {'t': 'setting', 'src': 'h_motion', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ms_sld', 'label': 'Empfindlichkeit', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_sens', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'keys_wake_btn', 'label': 'Tasten wecken', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_keys', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'dim_wake_btn', 'label': 'Aufhellen bei Bewegung', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_dim_wake', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'dim_hold_btn', 'label': 'Nicht abdunkeln bei Bewegung', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_dim_hold', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ds_sld', 'label': 'Empfindlichkeit (beide oben)', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_dim_sens', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'klopf_btn', 'label': 'Doppelt klopfen weckt', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'kl_sld', 'label': 'Klopf-Empfindlichkeit', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_klopf', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_touch_btn', 'label': 'Touch weckt', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_touch', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_touchms_sld', 'label': 'Touch-Abfrage', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_touchms', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Tiefschlaf', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_deep_btn', 'label': 'Tiefschlaf im Ruhezustand', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_deep', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_deepble_btn', 'label': 'Nur ohne Bluetooth', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'Solange Streamer, TV oder Tablet verbunden sind, kein Tiefschlaf: die Verbindung bleibt im Spartakt, kein '
                      'Neuverbinden und kein Bildzucken. WLAN geht trotzdem aus.',
             'w': 6,
             'h': 0},
            {'t': 'setting', 'src': 'ps_deeps_sld', 'label': 'Tiefschlaf nach', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_deeps', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ps_deeptv_sld', 'label': 'Tiefschlaf bei TV an', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_deeptv', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'AKKU', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_low_sld', 'label': 'Sparmodus bei Akku unter', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'ps_h_low', 'label': '', 'w': 6, 'h': 0}]},
 {'id': 'set_voice_set',
  'title': 'Sprache',
  'remember': True,
  'flow': True,
  'items': [{'t': 'setting', 'src': 'tile_assi', 'label': 'Assistent', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_assi', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'tile_google_mode', 'label': 'Google-Modus', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_google_mode', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'tile_tts', 'label': 'Antwort hörbar', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_tts', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'tile_mic', 'label': 'Mikrofon', 'w': 6, 'h': 1}]},
 {'id': 'set_ble',
  'title': 'Bluetooth',
  'remember': True,
  'flow': True,
  'items': [{'t': 'setting', 'src': 'ble_state_lbl', 'label': '', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_slot0', 'label': 'Google Streamer', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_slot1', 'label': 'TV', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_slot2', 'label': 'Tablet Wohnzimmer', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_slot3', 'label': 'Slot 4', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_target_lbl', 'label': '', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_connect', 'label': 'Verbinden', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_pair', 'label': 'Neu koppeln', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_forget', 'label': 'Kopplung löschen', 'w': 6, 'h': 1},
            {'t': 'text', 'label': 'Optionen', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_kbd_btn', 'label': 'Tastatur', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ble_kbd_hint', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'ble_par_btn', 'label': 'Parallel verbunden', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'AN: Beim Aktivitätswechsel bleibt die bisherige Verbindung bestehen (geparkt). Kein Neuladen von Videos beim '
                      'Wechseln, zurück ist sofort da. Im Tiefschlaf wird trotzdem getrennt.',
             'w': 6,
             'h': 0}]},
 {'id': 'set_akku',
  'title': 'Akku',
  'remember': True,
  'flow': True,
  'items': [{'t': 'setting', 'src': 'ak_status', 'label': 'Status', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_pct', 'label': 'Akkustand', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_volt', 'label': 'Spannung', 'w': 6, 'h': 1},
            {'t': 'text', 'label': 'Verbrauch', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_rate', 'label': 'Rate jetzt (Chip)', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_r1', 'label': 'Letzte Stunde', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_r24', 'label': 'Letzte 24 h', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_rest', 'label': 'Restlaufzeit', 'w': 6, 'h': 1},
            {'t': 'text', 'label': 'Laden', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_geladen', 'label': 'Zuletzt geladen', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_geladen2', 'label': '', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ak_schlaf', 'label': 'Tiefschlaf seit Ladung', 'w': 6, 'h': 1},
            {'t': 'text', 'label': 'Verlauf 24 h', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'Raten ohne Ladezeiten, aus Messpunkten alle 5 min - auch über den Tiefschlaf hinweg. Minus = Entladen.',
             'w': 6,
             'h': 0},
            {'t': 'special', 'page': 'akku', 'label': 'Verlauf (Grafik)', 'w': 6, 'h': 1}]},
 {'id': 'set_service',
  'title': 'Wartung & Tests',
  'remember': True,
  'flow': True,
  'items': [{'t': 'text', 'label': 'Tests', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'tile_touchtest', 'label': 'Touch-Test', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_touch', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'tile_button_test', 'label': 'Tasten-Test', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_btn', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Reinigung', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'clean_dur_sld', 'label': 'Reinigungsdauer', 'w': 6, 'h': 2},
            {'t': 'setting', 'src': 'h_cleandur', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'tile_clean', 'label': 'Reinigungsmodus', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_clean', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Sd-karte', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'tile_sd', 'label': 'SD-Karte', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_sd_tile', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Entwickler', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_log_btn', 'label': 'Debug-Log', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_log', 'label': '', 'w': 6, 'h': 0},
            {'t': 'setting', 'src': 'testmod_btn', 'label': 'Testmodus (immer online)', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'ps_h_test', 'label': '', 'w': 6, 'h': 0},
            {'t': 'text', 'label': 'Gerät', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'tile_shutdown', 'label': 'Gerät herunterfahren', 'w': 6, 'h': 1},
            {'t': 'text',
             'label': 'Tiefschlaf ohne Bewegungswecker. Nur die Aus-Taste oder das Ladekabel schalten wieder ein.',
             'w': 6,
             'h': 0},
            {'t': 'setting', 'src': 'tile_restart', 'label': 'Gerät neu starten', 'w': 6, 'h': 1},
            {'t': 'setting', 'src': 'h_restart', 'label': '', 'w': 6, 'h': 0}]}]
